version: "3.9"
services:
  backend:
    build: ./backend
    container_name: novabot-backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: novabot
      MONGO_INITDB_ROOT_USERNAME: localdev
      MONGO_INITDB_ROOT_PASSWORD: localdevpass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
  static_volume: